

-- Q1 :	OUT OF NOT NULL AND PRIMARY KEY, NOT NULL IS MORE POWER FULL.  HOW DO YOU PROOVE IT ?

-- Q2 :	CAN WE HAVE DUPLICATE VALUES IN FOREIGN KEY ?

-- Q3 : CAN WE DEFINE PRIMARY KEY ON CHARACTER COLUMNS ?

-- Q4 : CAN WE DEFINE MULTIPLE CONSTRAINTS IN A SINGLE COLUMN ?


/*
1. INTRODUCTION
2. INSTALLATION
3. SQL BASICS @ GUI
4. SQL BASICS @ QUERIES

5. EXCEL IMPORTS
6. SCHEMAS
7. CONSTAINTS
8. JOINS BASICS
9. INDEXES

10.  NOW: GROUP BY QUERIES
	THEN
	GROUP BY QUERIES WITH JOINS

	MANDATORY FOR DATA ANALYSTS, BUSINESS ANALYSTS, DATA ENGINEERS @ DATA EXTRACTION
	OPTIONAL FOR ENTRY LEVEL DBAS. MANDATORY FOR EXPERIENCED DBAs @ TUNING, AUDITING, MONITORING
*/



/*
DISTINCT:		THIS KEYWORD IS USED TO REPORT UNIQUE VALUES OF A COLUMN.

GROUP BY:		THIS KEYWORD IS USED TO REPORT UNIQUE VALUES OF A COLUMN & COMPUTE AGGREGATIONS LIKE SUM, AVG, COUNT, MAX...

HAVING	:		THIS KEYWORD IS USED TO SPECIFY CONDITIONS ON AGGREGATIONS.

QUERY FORMAT V1:
SELECT <<COLUMN-LIST>>  
FROM	<<TABLE-NAME>> 
WHERE	<<CONDITION>>
GROUP BY <<COLUMN-LIST>>
HAVING	<<CONDITION>>


QUERY FORMAT V2:
SELECT <<COLUMN-LIST>>  
FROM <<TABLE-NAME>>
<<JOIN TYPE>>  <<TABLE-NAME>>
ON		<<CONDITION>>
WHERE	<<CONDITION>>
GROUP BY <<COLUMN-LIST>>
HAVING	<<CONDITION>>
ORDER BY <COLUMN-NAME>
*/

CREATE DATABASE GROUPBY_PRACTICEDB


USE GROUPBY_PRACTICEDB


CREATE TABLE tblPopulation
(
Country VARCHAR(100),
[State] VARCHAR(100),
City VARCHAR(100),
Population INT
)


INSERT tblPopulation VALUES			('COUNTRY1', 'STATE1','CITY1',9 ),
	('COUNTRY1', 'STATE1','CITY2',8 ), 	('COUNTRY1', 'STATE2','CITY1',5.5), 
	('COUNTRY1', 'STATE2','CITY2',7.5), 	('COUNTRY2', 'STATE1','CITY1',9.5),
	('COUNTRY2', 'STATE1','CITY2',2.5),	('COUNTRY2', 'STATE2','CITY1',1.5),	
	('COUNTRY3', 'STATE1','CITY1',30),		('COUNTRY3', 'STATE1','CITY2',20)


-- QUERY 1: HOW TO REPORT LIST OF ALL POPULATION DETAILS?
SELECT * FROM tblPopulation


-- QUERY 2: HOW TO REPORT LIST OF ALL COUNTRY NAMES?
SELECT Country FROM tblPopulation


-- QUERY 3: HOW TO REPORT LIST OF ALL UNIQUE COUNTRIES DETAILS?
SELECT DISTINCT Country FROM tblPopulation 


-- QUERY 4: HOW TO REPORT LIST OF ALL UNIQUE COUNTRIES DETAILS?
SELECT Country FROM tblPopulation
GROUP BY Country


-- QUERY 5: HOW TO REPORT TOTAL POPULATION DETAILS?
SELECT sum(Population) AS TOTAL_POP FROM tblPopulation


-- RULE: WHENEVER WE USE GROUP BY, COLUMNS USED IN "SELECT" SHOULD BE IN GROUP BY. REMAINING COLUMNS IN AGGREGATE. 

-- QUERY 6: HOW TO REPORT COUNTRY WISE TOTAL POPULATION DETAILS?
SELECT		Country, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY	Country


-- QUERY 7: HOW TO REPORT COUNTRY WISE, STATE WISE  TOTAL POPULATION?
SELECT		COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY    COUNTRY     -- IN THIS QUERY, STATE IS NOT INCLUDED IN GROUP BY. HENCE, ERROR. 


SELECT		COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY    COUNTRY, STATE


-- QUERY 8: HOW TO REPORT COUNTRY WISE, STATE WISE, CITY WISE TOTAL POPULATION?
SELECT	 COUNTRY, STATE, CITY, sum(Population) AS TOTAL_POP FROM tblPopulation 
GROUP BY COUNTRY, STATE, CITY


-- QUERY 9: HOW TO APPLY CONDITIONS ON AGGREGATIONS ?
SELECT		COUNTRY, STATE, CITY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY	COUNTRY , STATE, CITY
HAVING		sum(Population) > 15				-- DEFINE CONDITIONS ON AGGREGATE


SELECT		COUNTRY, STATE, CITY, sum(Population) AS TOTAL_POP FROM tblPopulation
GROUP BY	COUNTRY , STATE, CITY
HAVING		sum(Population) > 1


-- QUERY 10: HOW TO APPLY CONDITIONS ON NON AGGREGATE COLUMNS (LIKE COUNTRY, STATE..) AND AGGREGATIONS (SUM())
SELECT COUNTRY, STATE, sum(Population) AS TOTAL_POP FROM tblPopulation
WHERE  COUNTRY = 'COUNTRY1'				-- TO SPECIFY CONDITIONS ON NON AGGREGATE COLUMNS  (country, state, city..)
GROUP BY STATE, COUNTRY
HAVING sum(Population) > 5				-- TO SPECIFY CONDITIONS ON AGGREGATE COLUMNS	 (sum(Population))


-- NEXT:		HOW TO USE JOINS & GROUP BY TOGETHER?
				HOW TO JOIN MORE THAN 2 TABLES?
