
CREATE DATABASE UNIVERSITYDATABASE

USE UNIVERSITYDATABASE

CREATE TABLE tblStudents
(
StdID int UNIQUE,				
StdName varchar(30) not null,	
StdAge int,
StdGender char,
StdCourse  varchar(30) CHECK (StdCourse IN ('COMPUTERS', 'ROBOTICS', 'CIVIL'))
)

INSERT INTO tblStudents VALUES (1001, 'JOHN', 30, 'M', 'COMPUTERS')
INSERT INTO tblStudents VALUES (1002, 'JOHNY', 40, 'M', 'COMPUTERS')
INSERT INTO tblStudents VALUES (1003, 'JENY', 30, 'F', 'ROBOTICS')
INSERT INTO tblStudents VALUES (1004, 'JENISH', 33, 'M', 'ROBOTICS')
INSERT INTO tblStudents VALUES (1005, 'JOHNY', 33, 'M', 'ROBOTICS')
INSERT INTO tblStudents VALUES (1006, 'AMIN', 33, 'M', 'COMPUTERS')
INSERT INTO tblStudents VALUES (1007, 'AMINI', 30, 'F', 'CIVIL')
INSERT INTO tblStudents VALUES (1008, 'AMINISH', 37, 'M', 'CIVIL')

SELECT * FROM tblStudents


-- REQ 1:	HOW TO REPORT COMPUTERS STUDENTS?
SELECT * FROM tblStudents WHERE STDCOURSE = 'COMPUTERS'


-- REQ 2:	HOW TO STORE ABOVE QUERY IN THE DATABASE? FOR EASY USAGE
CREATE VIEW VW_COMPUTERS_STUDENTS
AS
SELECT * FROM tblStudents WHERE STDCOURSE = 'COMPUTERS'


-- REQ 3:	HOW TO ACCESS OR TEST THE VIEW?
SELECT * FROM VW_COMPUTERS_STUDENTS


-- REQ 4:	HOW TO UPDATE THE BASE TABLE USING VIEW?
UPDATE VW_COMPUTERS_STUDENTS SET STDAGE = 50
SELECT * FROM tblStudents


-- REQ 5:	HOW TO DELETE THE BASE TABLE USING VIEW?
DELETE FROM VW_COMPUTERS_STUDENTS 
SELECT * FROM tblStudents


-- REQ 6:	HOW TO CREATE A VIEW FOR CIVIL STAFF MEMBERS? FOR EASY USAGE, FOR SECURED ACCESS
CREATE VIEW VW_CIVIL_STUDENTS
AS
SELECT * FROM tblStudents WHERE STDCOURSE = 'CIVIL'


-- REQ 7:	HOW TO INSERT DATA INTO STUDENTS TABLE USING ABOVE VIEW?
INSERT INTO VW_CIVIL_STUDENTS VALUES (2001, 'JENY', 40, 'F', 'CIVIL')
SELECT * FROM tblStudents

-- WHENEVER WE PERFORM DML OPERATIONS ON THE VIEW, BASE TABLE GETS AFFECTED. 
 










-- REQ 8: HOW TO CHECK DEFINITION OF A VIEW?
	-- OPTION 1:	FROM GUI: SSMS > OBJECT EXPLORER > DATABASE > VIEWS > RIGHT CLICK VIEW > SCRIPT: CREATE TO NEW QUERY
	-- OPTION 2:	USING "SP_HELPTEXT" SYSTEM STORED PROCEDURE (NEXT CHAPTER)


-- REQ 9: WHAT ARE THE SYSTEM VIEWS?
-- SYSTEM VIEWS: THESE VIEWS ARE AUTO CREATED DURING DATABASE CREATION. THESE ARE STORED IN DATABASE mdf [PRIMARY DATA FILE].
-- PREDEFINED VIEWS =  METADATA VIEWS:
SELECT * FROM SYS.DATABASES				-- THIS SYSTEM VIEW WILL REPORT ALL DATABASES IN THE CURRENTLY CONNECTED SERVER
SELECT * FROM SYS.SCHEMAS				-- THIS SYSTEM VIEW WILL REPORT ALL SCHEMAS IN THE CURRENTLY CONNECTED DATABASE
SELECT * FROM SYS.TABLES				-- THIS SYSTEM VIEW WILL REPORT ALL TABLES IN THE CURRENTLY CONNECTED DATABASE
SELECT * FROM SYS.COLUMNS				-- THIS SYSTEM VIEW WILL REPORT ALL COLUMNS IN THE CURRENTLY CONNECTED DATABASE
SELECT * FROM SYS.INDEXES				-- THIS SYSTEM VIEW WILL REPORT ALL INDEXES IN THE CURRENTLY CONNECTED DATABASE

SELECT * FROM SYS.VIEWS					-- THIS SYSTEM VIEW WILL REPORT ALL VIEWS IN THE CURRENTLY CONNECTED DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES		-- THIS SYSTEM VIEW WILL REPORT ALL TABLES & VIEWS IN THE CURRENT DATABASE.

SELECT * FROM SYS.OBJECTS				-- THIS SYSTEM VIEW WILL REPORT ALL SCHEMAS, TABLES, KEYS, CONSTRAINTS, VIEWS, SPs,... IN CURRENTLY CONNECTED DATABASE


-- REQ 10: HOW TO MODIFY THE VIEW DEFINITION?
ALTER VIEW VW_COMPUTERS_STUDENTS
AS
SELECT STDID, STDNAME, STDCOURSE FROM tblStudents WHERE STDCOURSE = 'COMPUTERS'


-- REQ 11: HOW TO DROP THE VIEW FROM DATABASE?
DROP VIEW VW_COMPUTERS_STUDENTS

SELECT * FROM tblStudents







