
Connect to the Amazon Database you created in your previous classes. 
Write TSQL Queries for below Requirements:

TASK 1:	HOW TO REPORT YEAR WISE SALES?
-- MEANS, WE NEED TO REPORT UNIQUE YEAR VALUES + TOTAL SALES FOR EACH YEAR
-- RULE: WHENEVER WE USE GROUP BY, THEN COLUMNS IN SELECT SHOULD BE EITHER IN GROUP BY OR IN AGGREGATE
SELECT YEAR, SUM(SaleAmount) FROM TIME_DATA 
INNER JOIN 
tblSales 
ON
TIME_DATA.TimeKey = tblSales.TimeKey
GROUP BY YEAR



TASK 2:	HOW TO REPORT YEAR WISE, QUARTER WISE TOTAL SALES?
SELECT YEAR, QUARTER,  SUM(SaleAmount) AS TOTALSALES FROM TIME_DATA 
INNER JOIN 
tblSales 
ON
TIME_DATA.TimeKey = tblSales.TimeKey
GROUP BY YEAR, QUARTER



TASK 3:	HOW TO REPORT YEAR WISE, QUARTER WISE, MONTH WISE TOTAL SALES?
SELECT YEAR, QUARTER, MONTH,  SUM(SaleAmount) AS TOTALSALES FROM TIME_DATA 
INNER JOIN 
tblSales 
ON
TIME_DATA.TimeKey = tblSales.TimeKey
GROUP BY YEAR, QUARTER, MONTH



TASK 4:	HOW TO REPORT YEAR WISE, QUARTER WISE, MONTH WISE, DAY WISE, PRODUCT WISE SALES FOR SUCH PRODUCTS WITH UNIT PRICE = 2
SELECT T.YEAR, T.QUARTER, T.MONTH, T.DAY, P.ProductName,
SUM(S.SaleAmount) AS TOTAL_SALES, AVG(S.TaxAmount) AS AVG_TAX
FROM TIME_DATA AS T
INNER JOIN 
tblSales   AS S
ON
T.TimeKey = S.TimeKey
JOIN 
PRODUCTS_DATA AS P
ON
P.ProductKey = S.ProductKey
WHERE P.UnitPrice = 2
GROUP BY T.YEAR, T.QUARTER, T.MONTH, T.DAY, P.ProductName



TASK 5:	HOW TO REPORT YEAR WISE, QUARTER WISE, MONTH WISE, DAY WISE, PRODUCT WISE SALES FOR SUCH PRODUCTS WITH MAXIMUM UNIT PRICE
SELECT T.YEAR, T.QUARTER, T.MONTH, T.DAY, P.ProductName,
SUM(S.SaleAmount) AS TOTAL_SALES, AVG(S.TaxAmount) AS AVG_TAX
FROM TIME_DATA AS T
INNER JOIN 
tblSales   AS S
ON
T.TimeKey = S.TimeKey
JOIN 
PRODUCTS_DATA AS P
ON
P.ProductKey = S.ProductKey
WHERE P.UnitPrice = (SELECT  MAX(UNITPRICE)   FROM PRODUCTS_DATA )
GROUP BY T.YEAR, T.QUARTER, T.MONTH, T.DAY, P.ProductName




TASK 6:	HOW TO REPORT YEAR WISE, QUARTER WISE, MONTH WISE, DAY WISE, PRODUCT WISE SALES FOR SUCH PRODUCTS WITH MAXIMUM UNIT PRICE ?
	REPORT ONLY SUCH DATA WITH TOTAL SALES ABOVE 10000?
SELECT T.YEAR, T.QUARTER, T.MONTH, T.DAY, P.ProductName,
SUM(S.SaleAmount) AS TOTAL_SALES, AVG(S.TaxAmount) AS AVG_TAX
FROM TIME_DATA AS T
INNER JOIN 
tblSales   AS S
ON
T.TimeKey = S.TimeKey
JOIN 
PRODUCTS_DATA AS P
ON
P.ProductKey = S.ProductKey
WHERE P.UnitPrice = (SELECT  MAX(UNITPRICE)   FROM PRODUCTS_DATA )
GROUP BY T.YEAR, T.QUARTER, T.MONTH, T.DAY, P.ProductName
HAVING SUM(S.SaleAmount) > 10000
ORDER BY TOTAL_SALES DESC						

 



/*
1. QUERY EXECUTION ORDER:		FROM > JOIN > WHERE > GROUP BY > HAVING > ORDER BY & SELECT
2. WE CAN USE TABLE ALIAS ANYWHERE IN THE ENTIRE QUERY
3. WE CAN USE COLUMN ALIAS ONLY IN ORDER BY & SELECT
4. WHERE		:	THIS KEYWORD IS USED FOR CONDITIONS ON NON AGGREGATE COLUMNS.	EX:  UNIT PRICE,  MONTH, QUARTER....
5. HAVING		:	THIS KEYWORD IS USED FOR CONDITIONS ON AGGREGATION VALUES.		EX:  SUM(SALES) 

6. WHENEVER WE OTPIMIZE ANY SQL QUERY, WE NEED TO CONSIDER THE EXECUTION ORDER.
*/
 






