
CREATE DATABASE DBTRIGERTEST

USE DBTRIGERTEST

create table Reservation
( 
Aircraft_Code varchar(10), 
No_of_Seats int, 
Class_Code varchar(10) 
)
					

-- ITEM #1:  HOW TO DEFINE A TRIGGER ON THE TABLE?
-- REQUIREMENT:	WHENEVER WE PERFORM DML OPERATION ON A TABLE, WE NEED TO PRINT A CONFIRMATION MESSAGE.	
CREATE TRIGGER trigAddnOpr
ON Reservation
FOR INSERT
AS
PRINT 'GIVEN DML OPERATION IS SUCCCESSFUL.'


-- ITEM #2: HOW TO TEST ABOVE TRIGGER?
INSERT INTO Reservation VALUES ('EMI01', 11, 'ECO')


-- ITEM #3: HOW TO LOCK A TABLE? HOW TO MAKE A TABLE READ ONLY?
CREATE TRIGGER trigALTOpr
ON Reservation
INSTEAD OF INSERT, UPDATE, DELETE
AS
PRINT 'TABLE IS READ ONLY. CONTACT YOUR ADMIN.'


-- ITEM #4: HOW TO TEST ABOVE TRIGGER?
UPDATE Reservation SET No_of_Seats = 0 
DELETE FROM Reservation  


-- ITEM #5: HOW TO DISABLE A TRGGER?
DISABLE TRIGGER trigALTOpr ON Reservation
DELETE FROM Reservation  
SELECT * FROM Reservation

-- ITEM #6: HOW TO ENABLE A TRGGER?
ENABLE TRIGGER trigALTOpr ON Reservation


-- ITEM #7: HOW TO VERIFY LIST OF TRIGGERS?
SELECT * FROM SYS.TRIGGERS 


-- ITEM #8: HOW TO VERIFY DEFINITION OF TRIGGER?
EXEC SP_HELPTEXT 'trigALTOpr'


-- ITEM #9: HOW TO MODIFY DEFINITION OF TRIGGER?
ALTER TRIGGER trigALTOpr
ON Reservation
INSTEAD OF INSERT, UPDATE					-- HERE, DML OPERATIONS ARE CALLED "EVENTS"
AS
PRINT 'TABLE IS READ ONLY. CONTACT YOUR ADMIN.'


-- ITEM #10: HOW TO VERIFY DEFINITION OF TRIGGER?
EXEC SP_HELPTEXT 'trigALTOpr'

-- ITEM #11: HOW TO DROP OR REMOVE TRIGGER FROM THE DATABASE?
DROP TRIGGER trigALTOpr


				

/*
SCHEMAS

TABLES

KEYS

CONSTRAINTS

INDEXES

VIEWS

PROCEDURES

FUNCTIONS

TRIGGERS
*/