/*
STATISTICS ARE DATABASE OBJECTS USED TO STORE COLUMN ADDRESS INFORMATION.
PURPOSE: FOR FASTER, EASIER COLUMN ACCESS. 

ADVANTAGE OF STATISTICS:
	ASSUME A TABLE WITH MULTIPLE COLUMNS.
	YOU USE ONE COLUMN IN A QUERY CONDITION. 
	THIS AUTO CREATES ONE STATISTICS ON THIS COLUMN.

	THEN THE NEXT TIME WE USE THE SAME COLUMN IN THE QUERIES, THE ABOVE CREATED STATISTICS ARE AUTO DETECTED, USED
	BY QO (QUERY OPTIMIZER) FOR ANALYSING THE BEST EXECUTION PLAN. 

	STATISTICS ARE AUTO CREATED WHEN:
	1. WE CREATE THE INDEX ON A COLUMN
	2. WE USE A COLUMN IN THE QUERY CONDITIONS

	ADDITIONALLY, WE CAN ALSO CREATE STATISTICS MANUALLY.
*/
	
CREATE DATABASE STATS_DB 

USE STATS_DB

CREATE TABLE TEST_TABLE (COL1 INT PRIMARY KEY, COL2 INT)
INSERT INTO TEST_TABLE VALUES (1001, 10), (1002, 10), (1003, 10), (1004, 10)

SELECT * FROM TEST_TABLE WHERE COL2 = 10		-- STATISTICS ARE AUTO CREATED.


-- HOW TO CREATE STATISTICS MANUALLY?
CREATE STATISTICS STATS2 ON TEST_TABLE (COL2)


-- TO MONITOR STATISTICS OF A TABLE:
SELECT * FROM SYS.STATS WHERE OBJECT_ID = OBJECT_ID('TEST_TABLE')	



-- HOW TO UPDATE THE STATISTICS MANUALLY?
UPDATE STATISTICS TEST_TABLE WITH FULLSCAN			-- EVERY PAGE FOR THIS TABLE IS SCANNED, UPDATED


-- INDEXES:		USED TO BOOKMARK THE COLUMN DATA
-- STATISTICS:	USED TO BOOKMARK THE COLUMN ADDRESS


/*
MAINTENENCE OF STATISTICS: 	
FOR EFFICIENT USE OF STATISTICS BY QUERY OPTIMIZER, WE NEED TO ENSURE THE STATS ARE UPTO DATE.
	OPTION 1:	MANUAL / ON-DEMAND UPDATE OF STATISTICS FOR A SPECIFIC TABLE
	OPTION 2:	AUTOMATED STATISTICS UPDATE OF ALL TABLES IN ALL DATABASES IN THE SERVER : MAINTENANCE PLANS

*/ 