
-- QUERY 1:	HOW TO CREATE NEW DATABASE?
CREATE DATABASE BANKDATABASE


-- QUERY 2:	HOW TO CONNECT TO ABOVE DATABASE?
USE BANKDATABASE


-- QUERY 3: HOW TO CREATE NEW SCHEMAS INSIDE ABOVE DATABASE?   
CREATE SCHEMA ACCOUNTS_SCHEMA 	  


CREATE SCHEMA INSURANCE_SCHEMA 


-- QUERY 4: HOW TO USE ABOVE SCHEMA, CREATE TABLES?
CREATE TABLE ACCOUNTS_SCHEMA.tblSavingAccounts
(
AccountID int,
AccBal float,
AccStatus bit			-- THIS DATA TYPE IS USED TO STORE Os AND 1s
)

INSERT INTO ACCOUNTS_SCHEMA.tblSavingAccounts 	VALUES (1001, 999999.99, 1)
INSERT INTO ACCOUNTS_SCHEMA.tblSavingAccounts 	VALUES (1002, 9999.99, 1)
INSERT INTO ACCOUNTS_SCHEMA.tblSavingAccounts 	VALUES (1003, 9999999.99, 0)
INSERT INTO ACCOUNTS_SCHEMA.tblSavingAccounts 	VALUES (1004, 9999.99, 1)


SELECT * FROM ACCOUNTS_SCHEMA.tblSavingAccounts	  



CREATE TABLE ACCOUNTS_SCHEMA.tblCurrentAccounts
(
AccountID int,
AccBal float,
AccStatus bit			-- THIS DATA TYPE IS USED TO STORE Os AND 1s
)

INSERT INTO ACCOUNTS_SCHEMA.tblCurrentAccounts 	VALUES (10001, 999999.99, 1)
INSERT INTO ACCOUNTS_SCHEMA.tblCurrentAccounts 	VALUES (10002, 9999.99, 1)
INSERT INTO ACCOUNTS_SCHEMA.tblCurrentAccounts 	VALUES (10003, 9999999.99, 0)
INSERT INTO ACCOUNTS_SCHEMA.tblCurrentAccounts 	VALUES (10004, 9999.99, 1)

SELECT * FROM ACCOUNTS_SCHEMA.tblCurrentAccounts


CREATE TABLE INSURANCE_SCHEMA.tblHealthInsurance (InsID int, InsPremiumBal float, SSN varchar(30) )
CREATE TABLE INSURANCE_SCHEMA.tblVehicleInsurance (InsID int, InsPremiumBal float, RegNumber varchar(30) )
CREATE TABLE INSURANCE_SCHEMA.tblTravelInsurance (InsID int, InsPremiumBal float, PasspostNumber varchar(30) )
 

INSERT INTO INSURANCE_SCHEMA.tblHealthInsurance 	VALUES (1001, 999999.99, 'ABC12345-90')
INSERT INTO INSURANCE_SCHEMA.tblHealthInsurance 	VALUES (1002, 999999.99, 'ABC12346-90')	

SELECT * FROM INSURANCE_SCHEMA.tblHealthInsurance
 
 
-- WHAT IF WE CREATE A TABLE WITHOUT MENTIONING ANY SCHEMA?
-- SUCH TABLES WILL BE STORED IN "dbo" SCHEMA (DATABASE OWNER). 
CREATE TABLE tblLoanInsurance
(
InsID int,
InsPremiumBal float,
LoanNumber varchar(30)			 
)	


-- RULE: IF TABLE BELONGS TO dbo SCHEMA, THEN WE NEED NOT MENTION THE SCHEMA NAME IN QUERIES.
INSERT INTO tblLoanInsurance 		VALUES (101, 9999.99, 'LN09-09676')
INSERT INTO DBO.tblLoanInsurance 	VALUES (102, 999.99, 'LN09-09677')	    


SELECT * FROM tblLoanInsurance
SELECT * FROM dbo.tblLoanInsurance


-- HOW TO MOVE (MIGRATE) A TABLE FROM "DBO" SCHEMA TO "INSURANCE_SCHEMA" ?
-- FORMAT:   ALTER SCHEMA <<TARGET-SCHEMA>> TRANSFER <<SOURCE-SCHEMA>>.<<SOURCE-TABLE>>

-- REQUIREMENT: HOW TO MOVE "tblLoanInsurance" TABLE FROM DBO TO INSURANCE_SCHEMA?

ALTER SCHEMA INSURANCE_SCHEMA TRANSFER DBO.tblLoanInsurance

-- HOW TO VERIFY ABOVE TABLE MIGRATION FROM ONE SCHEMA TO ANOTHER?
SELECT * FROM INSURANCE_SCHEMA.tblLoanInsurance

SELECT * FROM INSURANCE_SCHEMA.tblLoanInsurance										-- 2 PART NAMING
SELECT * FROM BANKDATABASE.INSURANCE_SCHEMA.tblLoanInsurance						-- 3 PART NAMING
SELECT * FROM [DESKTOP-P5N46MK].BANKDATABASE.INSURANCE_SCHEMA.tblLoanInsurance		-- 4 PART NAMING



































-- HOW TO MIGRATE OR MOVE A TABLE FROM ONE SCHEMA TO ANOTHER?
-- SYNTAX:	ALTER SCHEMA <<TARGET-SCHEMA>> TRANSFER <<SOURCE-SCHEMA>>.<<SOURCE TABLE>>
-- EXAMPLE: HOW TO MOVE tblLoanInsurance  TABLE FROM dbo SCHEMA TO INSURANCE_SCHEMA ?
ALTER SCHEMA INSURANCE_SCHEMA TRANSFER DBO.tblLoanInsurance
SELECT * FROM  INSURANCE_SCHEMA.tblLoanInsurance


-- HOW TO VERIFY IF THE TABLE IS MIGRATED OR NOT?


ALTER SCHEMA INSURANCE_SCHEMA TRANSFER DBO.tblLoanInsurance
SELECT * FROM INSURANCE_SCHEMA.tblLoanInsurance


