
-- QUERY 1: 
CREATE DATABASE UNIVERSITY_DATABASE2


-- QUERY 2:
USE UNIVERSITY_DATABASE2


-- QUERY 3:
CREATE TABLE TBLCOURSES
(
COURSE_ID INT PRIMARY KEY,			-- THIS COLUMN DOES NOT ALLOW NULLS. DOES NOT ALLOW DUPLICATES.	
COURSE_NAME VARCHAR(30) NOT NULL,	-- THIS COLUMN DOES NOT ALLOW NULLS	
COURSE_DUR INT CHECK (COURSE_DUR = 120 OR COURSE_DUR  = 180) -- THIS COLUMN ALLOWS ONLY 120 OR 180
)

-- QUERY 4: 
INSERT INTO TBLCOURSES VALUES (101, 'COMPUTERS', 120)
INSERT INTO TBLCOURSES VALUES (102, 'ROBOTICS', 180)


-- QUERY 5: 
SELECT * FROM TBLCOURSES

INSERT INTO TBLCOURSES VALUES (102,'CIVIL', 180)	-- ERROR.ID IS DUPLICATED
INSERT INTO TBLCOURSES VALUES (103, NULL, 180)		-- ERROR.COURSE NAME CANNOT BE NULL
INSERT INTO TBLCOURSES VALUES (103,'CIVIL',-180)	-- ERROR.INVALID DURATION

SELECT * FROM TBLCOURSES






-- QUERY 6: 
CREATE TABLE TBLSTUDENTS
(
STD_ID INT UNIQUE,				-- THIS COLUMN DOES NOT ALLOW DUPLICATES. BUT ALLOW UPTO 1 NULL VALUE.
STD_NAME VARCHAR(30) NOT NULL,	-- THIS COLUMN DOES NOT ALLOW NULLS
STD_AGE INT CHECK (STD_AGE >= 18),
STD_COURSE_ID INT REFERENCES TBLCOURSES (COURSE_ID)  -- THIS COLUMN VALUE SHOULD MATCH WITH TBLCOURSES : COURSE_ID
)


-- QUERY 7: 
INSERT  INTO  TBLSTUDENTS VALUES (1001, 'SAI', 34, 101)		-- THIS STUDENT IS REGISTERING FOR COMPUTERS COURSE
INSERT  INTO  TBLSTUDENTS VALUES (1002, 'JON', 34, 101)		-- THIS STUDENT IS REGISTERING FOR COMPUTERS COURSE
INSERT  INTO  TBLSTUDENTS VALUES (1003, 'JOHNE', 34, 102)	-- THIS STUDENT IS REGISTERING FOR ROBOTICS COURSE
INSERT  INTO  TBLSTUDENTS VALUES (1004, 'JOHNY', 34, 102)	-- THIS STUDENT IS REGISTERING FOR ROBOTICS COURSE


-- QUERY 8: 
SELECT * FROM TBLSTUDENTS


-- QUERY 9: HOW TO TEST UNIQUE KEY?
INSERT  INTO  TBLSTUDENTS VALUES (1004, 'JENY', 34, 102)	--ERROR. REASON : DUPLICATE STUDENT ID


-- QUERY 10: HOW TO TEST FOREIGN KEY?
INSERT  INTO  TBLSTUDENTS VALUES (1005, 'JENY', 34, 103)	--ERROR. REASON : INVLAID COURSE ID



-- QUERY 11: 
CREATE TABLE TBLSTAFF
(
STF_ID INT IDENTITY(100001, 1),							-- SEQUENCE VALUE GENERATION. START VALUE IS CALLED "SEED". 2ND VALUE IS CALLED "STEP" OR INCREMENT	
STF_NAME VARCHAR(30) NOT NULL,		
STF_GENDER CHAR CHECK (STF_GENDER = 'M' OR STF_GENDER = 'F') DEFAULT 'F',
STF_COURSE_ID INT REFERENCES tblcourses(course_id)		-- THIS COLUMN VALUE SHOULD MATCH WITH TBLCOURSES : COURSE_ID
)


-- QUERY 12:	
INSERT INTO TBLSTAFF VALUES 	('JOHN',  'M', 101)			-- THIS STAFF MEMBER BELONGS TO COMPUTERS DEPT.
INSERT INTO TBLSTAFF VALUES     ('JOHNY',  'M', 101)		-- THIS STAFF MEMBER BELONGS TO COMPUTERS DEPT.


-- QUERY 13: 
SELECT * FROM TBLSTAFF		


-- QUERY 14: HOW TO INSERT DEFAULT VALUE INTO STF_GENDER COLUMN?
-- RULE : DURING INSERTION: WE NEED TO SPECIFY REMAINING COLUMNS AND THEIR VALUES. MISSING COLUMNS WILL TAKE DEFAULT VALUES. 
INSERT INTO TBLSTAFF (STF_NAME, STF_COURSE_ID) VALUES ('AMI', 102)			-- STF_GENDER COLUMN IS MISSING
SELECT * FROM TBLSTAFF		


-- QUERY 15: 
SELECT * FROM TBLSTAFF		

INSERT INTO TBLSTAFF  VALUES ('AMIN', 102)   -- ERROR