-- TASK 1: WRITE A QUERY TO REPORT LIST OF PRODUCTS, RESPECTIVE SALES? 
SELECT* FROM PRODUCTS_DATA
JOIN SALES_DATA
ON PRODUCTS_DATA.ProductID = SALES_DATA.SaleProductID


-- TASK 2: WRITE A QUERY TO REPORT LIST OF PRODUCTS WITHOUT ANY SALES? 
SELECT* FROM PRODUCTS_DATA
LEFT JOIN SALES_DATA
ON PRODUCTS_DATA.ProductID = SALES_DATA.SaleProductID
WHERE SALES_DATA.SaleProductID IS NULL


-- TASK 3: WRITE A QUERY TO REPORT LIST OF PRODUCTS WITH SALES, PRODUCTS WITHOUT SALES? 
SELECT* FROM PRODUCTS_DATA
LEFT JOIN SALES_DATA
ON PRODUCTS_DATA.ProductID = SALES_DATA.SaleProductID
 

SELECT* FROM PRODUCTS_DATA
RIGHT JOIN SALES_DATA
ON PRODUCTS_DATA.ProductID = SALES_DATA.SaleProductID


-- TASK 4: WRITE A QUERY TO REPORT  SALES FOR CAPS? 
SELECT* FROM PRODUCTS_DATA
INNER JOIN SALES_DATA
ON PRODUCTS_DATA.ProductID = SALES_DATA.SaleProductID
WHERE ProductName = 'CAPS'


-- TASK 5: WRITE A QUERY TO REPORT  SALES FOR CAPS AND GLOVES? 
SELECT* FROM PRODUCTS_DATA
INNER JOIN SALES_DATA
ON PRODUCTS_DATA.ProductID = SALES_DATA.SaleProductID
WHERE ProductName IN ('CAPS', 'GLOVES')
