
CREATE DATABASE RANK_FUNCTIONS_DB


USE RANK_FUNCTIONS_DB



CREATE TABLE tblInventory  
( 
ID INT NOT NULL, 
TitleTag NVARCHAR(30) NOT NULL, 
Measure INT NOT NULL DEFAULT 0 
)


INSERT INTO tblInventory VALUES (1, 'Comedy', 100),  (2, 'NEGOT', 100), (3, 'BUSINESS', 100)
INSERT INTO tblInventory VALUES	(4, 'PB CHAPTER BKS', 200),  (5, 'BEG READER HC', 200),  (6, 'Literature', 200)

SELECT * FROM tblInventory		 


-- REQUIREMENT :	HOW TO RANK THE DATA? WINDOW FUNCTIONS (RANK FUNCTIONS)?
/* THREE RANK FUNCTIONS:  
	ROW_NUMBER()	:		A UNIQUE SEQUENCE IS AUTO GENERATED FOR EVERY ROW. SIMILAR TO IDENTITY.
	RANK()			:		SAME SEQUENCE GENERATED FOR A COLUMN THAT HAS SIMILAR VALUE. NEW VALUE RESULTS IN ROW NUMBER.			
	DENSE_RANK()	:		SAME SEQUENCE GENERATED FOR A COLUMN THAT HAS SIMILAR VALUE. NEW VALUE RESULTS IN NEXT SEQUENCE.

*	PARTITION BY	:		SAME VALUE FOR GIVEN COLUMN RESULTS IN ONE SEQUENCE. NEW VALUE RESULTS IN RESET OF SEQUENCE.

*/ 

SELECT *, ROW_NUMBER() OVER (ORDER BY Measure) as SEQ1 FROM tblInventory

SELECT *, RANK() OVER (ORDER BY Measure) as SEQ2 FROM tblInventory

SELECT *, DENSE_RANK() OVER (ORDER BY Measure) as SEQ3 FROM tblInventory

SELECT *, ROW_NUMBER() OVER (PARTITION BY Measure ORDER BY Measure) as SEQ4 FROM tblInventory


-- REAL-WORLD USE OF WINDOW FUNCTIONS?
-- REQ: HOW TO IDENTIFY DUPLICATE ROWS IN A TABLE ? HOW TO DELETE THEM ?	 DATA CLEANSING

-- INSERT DUPLICATED ROWS INTO THE TABLE
INSERT tblInventory VALUES   (3, 'BUSN PROFILES', 300),  (4, 'PB CHAPTER BKS', 200)  
INSERT tblInventory VALUES   (3, 'BUSN PROFILES', 300),  (4, 'PB CHAPTER BKS', 200)  


-- STEP 1:	HOW TO IDENTIFY DUPLICATED ROWS? 
SELECT *, ROW_NUMBER() OVER (PARTITION BY id, TitleTag, Measure ORDER BY id, TitleTag, Measure) as SEQ FROM tblInventory


-- STEP 2:	HOW TO DELETE THE DUPLICATED ROWS?
CREATE VIEW VW_DUPL_ROW_IDENTF
AS
SELECT *, ROW_NUMBER() OVER (PARTITION BY id, TitleTag, Measure ORDER BY id, TitleTag, Measure) as SEQ FROM tblInventory


SELECT * FROM	VW_DUPL_ROW_IDENTF WHERE SEQ > 1			-- THIS IS TO IDENTIFY THE DUPLICATED ROWS IN THE TABLE

DELETE FROM		VW_DUPL_ROW_IDENTF WHERE SEQ > 1			-- THIS IS TO REMOVE / DELETE THE DUPLICATED ROWS IN THE TABLE


-- STEP 3:	VERIFY THAT DUPLICATED ROWS ARE REMOVED FROM THE TABLE?
SELECT * FROM VW_DUPL_ROW_IDENTF











